name: Rust CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Update Rust Version to the Latest
        run: |
          rustup self update
          rustup update stable
          rustup default stable
          rustup component add clippy rustfmt
      - name: Output Rust Version
        run: rustup --version
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Clippy
        run: cargo clippy
      - name: Format
        run: cargo fmt --check
      - name: Doc
        run: cargo doc -vv
      - name: Build Debug
        run: cargo build --verbose
      - name: Run Tests Debug
        run: cargo test --verbose
      - name: Build Release
        run: cargo build --release --verbose
      - name: Run Tests Release
        run: cargo test --release --verbose
